### ISSUE TITLE
no of features in reality and imported ones?

### ISSUE THREAD

**Issue by marwa38** [MolinLab/Holomics#13]
Hi team 

no of features are 18984

```
dim(fbmn_stats_norm)
#[1]   480 18984
```

while after importing them, features are only 4 
![image](https://github.com/user-attachments/assets/06c295eb-ca71-4f77-a103-1ea896bc4e8e)
[downstream.zip](https://github.com/user-attachments/files/16948804/downstream.zip)

I below attached the features table along with one metadata table in case needed as .zip file. 
Any advice?

Many thanks in advance
Marwa

**Comment by kathi-munk** [comment]
Dear Marwa, 
sorry for the late reply, but I finally had a chance to have a look at your dataset.

When uploading a dataset to Holomics a filtering algorithm runs over the datasets if the number of features is higher than 10k.
The algorithmn first performs a low count filtering, meaning it removes all feature columns that have a column sum < 10.
Afterwards, if there a still more than 10k features, MAD filtering is applied.

The problem we have with your dataset is that only 4 feature columns have a sum > 10. Therefore, only these 4 features remain in the dataset. To prevent this maybe a transformation of the values to a higher value range could be performed to prevent them from being filtered.

Best, 
Katharina

**Comment by marwa38** [comment]
Thanks for your reply. Could you please suggest some examples for transformation of the values to a higher value range? multiplying by 100 for example?

**Comment by evasehr** [comment]
> Thanks for your reply. Could you please suggest some examples for transformation of the values to a higher value range? multiplying by 100 for example?

Dear Marwa,

may I add some comments here: in principle, if you have a count table (eg. read counts from transcriptomics or ASV table from microbial community analysis) and you want to circumvent the filtering of the low reads, multiplying with x would be an option. However, your input file looks like a table of p-values. Here, I doubt that a multiplication does make sense. Why don't you use a read count table instead, as recommended?

Kind regards
