### ISSUE TITLE
error due to many componenets in PLS-DA?

### ISSUE THREAD

**Issue by marwa38** [MolinLab/Holomics#6]
error when I have many components in PLS-DA? i get the error after component 9 (repeated it and got the same error).
![image](https://github.com/MolinLab/Holomics/assets/68851733/ca36b593-1db3-412d-b38c-36a4dd3db29e)
![image](https://github.com/MolinLab/Holomics/assets/68851733/e9eaa223-f129-4889-b1e1-aabb4d88290d)
Please note that I get in PCA the following:
![image](https://github.com/MolinLab/Holomics/assets/68851733/9082f777-ef3e-44a4-ac66-d9b251e4e7d4)

**Comment by kathi-munk** [comment]
Hello, please try to set the component parameter in the analysis parameters block to 9. This parameters works as an upper border for the tuning algorithm and calculates therefore only the first 9 components and plots them.

**Comment by marwa38** [comment]
i selected only 9, and the error still there
![image](https://github.com/MolinLab/Holomics/assets/68851733/bd294aa0-3a3d-4cbb-ad35-2a8ae5d0572f)

**Comment by kathi-munk** [comment]
Hello, for the PCA the "Number of components" parameter only influences how many components are visualized in the plots, but not how many are calculated in the background to get at least 80% explained variance - so this warning will always appear for your dataset as the calculation time would be indeterminable high. This is why we advise to use the PLS-DA, where the parameter does affect the number of components that are calculated (see my comment above).

**Comment by marwa38** [comment]
Thanks very for your comment and for clarifying.
