### ISSUE TITLE
any solution for the size issue?

### ISSUE THREAD

**Issue by marwa38** [MolinLab/Holomics#9]
Hi team 
Could you please help with how to use your package on a size of 15megabytes excel file?
It is not working on a such a big size. Please note that the features don't exceed 10,000. 
we tried to reduce the size of the file (by removing sammples) and it worked but we need to include all samples. 
![image](https://github.com/MolinLab/Holomics/assets/68851733/1323f8aa-4c03-44b3-841e-837a229628d9)

Cheers
Marwa

**Comment by kathi-munk** [comment]
Hi Marwa,
as a hotfix try running
`options(shiny.maxRequestSize = 20*1024^2)`
before running 
`Holomics::run_app()`.

This should increase the upload size to 20 MB. You can increase/decrease that by adjusting the numbers in the options call.

**Comment by marwa38** [comment]
All the datasets I am currenlty working on are having more than 10,000 features, do you think it would be great if there is a possibility to include all features?

**Comment by kathi-munk** [comment]
The recommendation to use 10k or less features comes directly from mixOmics, which is the base package for our analysis ([https://mixomicsteam.github.io/mixOmics-Vignette/id_01.html](url)) - we automated the filtering in a way that first the mixMc pipeline runs, if it is microbiome data, and additionally or for any other type of data if there are more than 10k features they get filtered down according to the Median Absolute Deviation.

For now it is not possible for the user to turn off this filtering and currently a change of this situation is not planned.

**Comment by marwa38** [comment]
Very cool, thanks for sharing those details, I think that is quite helpful to know as most of the metabolomics datasets are quite big (exceeding 10K features) and having away to work around quite useful.
